language: go

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

os:
  - linux

go:
  - tip # Go version is defined by the build container in the Dockerfile

env:
  - GORACE="halt_on_error=1"
    SOURCE_VERSION=$(source ./build-version.txt && echo -n $SOURCE_VERSION)
    SOURCE_REPO=$(source ./build-version.txt && echo -n $SOURCE_REPO)
    BUILD_VERSION=$(echo ${TRAVIS_COMMIT} | cut -c 1-10)

script:
  - docker build --pull --no-cache -t "iov1/tendermint:${BUILD_VERSION}" --build-arg source_version=${SOURCE_VERSION} --build-arg source_repo=${SOURCE_REPO} -f ./Dockerfile .

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_TAG" == "" ]] && [[ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag  "iov1/tendermint:${BUILD_VERSION}" "iov1/tendermint:latest" ;
    docker push "iov1/tendermint:latest";
    docker logout;
    fi
  # build the tagged image
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$TRAVIS_TAG" != "" ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag  "iov1/tendermint:${BUILD_VERSION}" "iov1/tendermint:$TRAVIS_TAG" ;
    docker push "iov1/tendermint:$TRAVIS_TAG";
    docker logout;
    fi
notifications:
  email: false

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
